export const transfiguredGems: string[] = [
    "Ice Nova of Frostbolts",
    "Ice Nova of Deep Freeze",
    "Leap Slam of Groundbreaking",
    "Blade Flurry of Incision",
    "Ground Slam of Earthshaking",
    "Cleave of Rage",
    "Double Strike of Impaling",
    "Double Strike of Momentum",
    "Lacerate of Butchering",
    "Lacerate of Haemorrhage",
    "Elemental Hit of the Spectrum",
    "Dual Strike of Ambidexterity",
    "Frenzy of Onslaught",
    "Detonate Dead of Scavenging",
    "Detonate Dead of Chain Reaction",
    "Volatile Dead of Confinement",
    "Volatile Dead of Seething",
    "Split Arrow of Splitting",
    "Cold Snap of Power",
    "Raise Zombie of Slamming",
    "Raise Zombie of Falling",
    "Caustic Arrow of Poison",
    "Righteous Fire of Arcane Devotion",
    "Discharge of Misery",
    "Flicker Strike of Power",
    "Spark of the Nova",
    "Spark of Unpredictability",
    "Ice Spear of Splitting",
    "Raise Spectre of Transience",
    "Infernal Blow of Immolation",
    "Glacial Hammer of Shattering",
    "Viper Strike of the Mamba",
    "Summon Skeletons of Archers",
    "Summon Skeletons of Mages",
    "Heavy Strike of Trarthus",
    "Dominating Blow of Inspiring",
    "Rain of Arrows of Artillery",
    "Rain of Arrows of Saturation",
    "Firestorm of Meteors",
    "Firestorm of Pelting",
    "Lightning Strike of Arcing",
    "Power Siphon of the Archmage",
    "Puncture of Shanking",
    "Lightning Arrow of Electrocution",
    "Burning Arrow of Vigour",
    "Icicle Mine of Fanning",
    "Icicle Mine of Sabotage",
    "Bear Trap of Skewers",
    "Fire Trap of Blasting",
    "Ethereal Knives of Lingering Blades",
    "Ethereal Knives of the Massacre",
    "Ice Shot of Penetration",
    "Arc of Surging",
    "Arc of Oscillating",
    "Holy Flame Totem of Ire",
    "Incinerate of Expanse",
    "Incinerate of Venting",
    "Cyclone of Tumult",
    "Reave of Refraction",
    "Lightning Trap of Sparking",
    "Animate Guardian of Smiting",
    "Spectral Shield Throw of Shattering",
    "Spectral Shield Throw of Trarthus",
    "Spectral Throw of Materialising",
    "Spectral Throw of Trarthus",
    "Animate Weapon of Self Reflection",
    "Animate Weapon of Ranged Arms",
    "Storm Call of Trarthus",
    "Flameblast of Celerity",
    "Flameblast of Contraction",
    "Barrage of Volley Fire",
    "Ball Lightning of Orbiting",
    "Ball Lightning of Static",
    "Summon Raging Spirit of Enormity",
    "Flame Surge of Combusting",
    "Glacial Cascade of the Fissure",
    "Molten Strike of the Zenith",
    "Pyroclast Mine of Sabotage",
    "Tornado Shot of Cloudburst",
    "Lightning Tendrils of Eccentricity",
    "Lightning Tendrils of Escalation",
    "Kinetic Blast of Clustering",
    "Blink Arrow of Bombarding Clones",
    "Blink Arrow of Prismatic Clones",
    "Mirror Arrow of Bombarding Clones",
    "Mirror Arrow of Prismatic Clones",
    "Summon Chaos Golem of Hordes",
    "Summon Chaos Golem of the Maelström",
    "Summon Ice Golem of Hordes",
    "Summon Ice Golem of Shattering",
    "Summon Flame Golem of Hordes",
    "Summon Flame Golem of the Meteor",
    "Summon Lightning Golem of Hordes",
    "Ice Crash of Cadence",
    "Flame Dash of Return",
    "Frost Blades of Katabasis",
    "Wild Strike of Extremes",
    "Ice Trap of Hollowness",
    "Blast Rain of Trarthus",
    "Galvanic Arrow of Energy",
    "Galvanic Arrow of Surging",
    "Bladefall of Volleys",
    "Bladefall of Impaling",
    "Bladefall of Trarthus",
    "Blade Vortex of the Scythe",
    "Frost Bomb of Instability",
    "Frost Bomb of Forthcoming",
    "Siege Ballista of Splintering",
    "Siege Ballista of Trarthus",
    "Summon Stone Golem of Hordes",
    "Summon Stone Golem of Safeguarding",
    "Earthquake of Amplification",
    "Contagion of Subsiding",
    "Contagion of Transference",
    "Blight of Contagion",
    "Blight of Atrophy",
    "Essence Drain of Desperation",
    "Essence Drain of Wickedness",
    "Sunder of Earthbreaking",
    "Sunder of Trarthus",
    "Vortex of Projection",
    "Dark Pact of Trarthus",
    "Scorching Ray of Immolation",
    "Cremation of Exhuming",
    "Cremation of the Volcano",
    "Bodyswap of Sacrifice",
    "Tectonic Slam of Cataclysm",
    "Explosive Trap of Shrapnel",
    "Explosive Trap of Magnitude",
    "Lightning Spire Trap of Zapping",
    "Lightning Spire Trap of Overloading",
    "Seismic Trap of Swells",
    "Consecrated Path of Endurance",
    "Smite of Divine Judgement",
    "Scourge Arrow of Menace",
    "Toxic Rain of Sporeburst",
    "Toxic Rain of Withering",
    "Summon Holy Relic of Conviction",
    "Lancing Steel of Spraying",
    "Storm Brand of Indecision",
    "Shattering Steel of Ammunition",
    "Armageddon Brand of Volatility",
    "Armageddon Brand of Recall",
    "Purifying Flame of Revelations",
    "Soulrend of Reaping",
    "Soulrend of the Spiral",
    "Bane of Condemnation",
    "Wave of Conviction of Trarthus",
    "Divine Ire of Holy Lightning",
    "Divine Ire of Disintegration",
    "Bladestorm of Uncertainty",
    "Perforate of Duality",
    "Perforate of Bloodshed",
    "Chain Hook of Trarthus",
    "Frostblink of Wintry Blast",
    "Summon Carrion Golem of Hordes",
    "Summon Carrion Golem of Scavenging",
    "Shrapnel Ballista of Steel",
    "Artillery Ballista of Cross Strafe",
    "Artillery Ballista of Focus Fire",
    "Stormbind of Teleportation",
    "Kinetic Bolt of Fragmentation",
    "Blade Blast of Unloading",
    "Blade Blast of Dagger Detonation",
    "Penance Brand of Dissipation",
    "Penance Brand of Conduction",
    "Earthshatter of Fragility",
    "Earthshatter of Prominence",
    "Void Sphere of Rending",
    "Crackling Lance of Branching",
    "Crackling Lance of Disintegration",
    "Splitting Steel of Ammunition",
    "Hexblast of Contradiction",
    "Hexblast of Havoc",
    "Exsanguinate of Transmission",
    "Rage Vortex of Berserking",
    "Spectral Helix of Trarthus",
    "Absolution of Inspiring",
    "Forbidden Rite of Soul Sacrifice",
    "Blade Trap of Greatswords",
    "Blade Trap of Laceration",
    "Storm Rain of the Conduit",
    "Storm Rain of the Fence",
    "Shield Crush of the Chieftain",
    "Summon Reaper of Revenants",
    "Summon Reaper of Eviscerating",
    "Boneshatter of Complex Trauma",
    "Boneshatter of Carnage",
    "Explosive Concoction of Destruction",
    "Eye of Winter of Finality",
    "Eye of Winter of Transience",
    "Poisonous Concoction of Bouncing",
    "Tornado of Elemental Turbulence",
    "Lightning Conduit of the Heavens",
    "Galvanic Field of Intensity",
    "Volcanic Fissure of Snaking",
    "Frozen Legion of Rallying",
    "Kinetic Rain of Impact",
];
